'admin_bar'            => false,
 'dev_mode'             => false,
 'update_notice'        => false,
 'customizer'           => false,
 'save_defaults'        => true,
 'show_import_export'   => false,
 'output'               => false,
'output_tag'           => false,
